-- insert into shopping.supplier( suppliername)
-- values( "Rainbow Supplies"),
--       ("Supplies Are Us"),
--       ("Random Supplies");
--
-- insert into shopping.product (productdescription, productimage, productname, productprice)
-- values("something to hold your coffee", "urlcup", "Coffee Mug", 5.79),
--       ("to wear", "url.shirt", "T-Shirt", 10.99),
--       ("glass-cleaner", "url.windex", "Windex", 3.88);
--
-- insert into shopping.productsuppliers
-- values(1,3),
--       (1,1),
--       (2,3),
--       (2,1),
--       (3,2),
--       (3,3);
--
-- insert into shopping.customer
-- values(222, "567 Apple Rd", "molly@email.com", "Molly", "857-483-9483", "VISA", "567 Apple Rd"),
--       (333, "938 Dear Ave", "gina@email.com", "Gina", "483-393-8475", "MasterCard", "9484 Morrow st");
--
-- insert into shopping.cart (cartname,custid)
-- values("Ginas Cart", 333),
--       ("Molly's Cart", 222);
--
-- insert into shopping.orders
-- values (690, true, "02/23/2019", 333);
--
-- insert into shopping.item (itemid,bought,incart,productid)
-- values (400, false, false, 3),
--        (401, false, false, 3),
--        (502, false, false, 2),
--        (700, false, false, 1);
--
-- insert into shopping.item (itemid,bought,incart,cartid, productid)
-- values (420, false, true, 2, 3),
--        (730, false, true, 2, 1);
--
--
-- insert into shopping.item (itemid,bought,incart,cartid, orderid, productid)
-- values (539, true,false, 2, 690, 2);



